# Copyright © 2023 Horizoncd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.1
info:
  title: Horizon-Pipelinerun-Restful
  version: 2.0.0
servers:
  - url: "http://localhost:8080/"
paths:
  /apis/core/v2/pipelineruns/{pipelinerunID}/stop:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    post:
      tags:
        - pipelinerun
      operationId: stopPipelinerun
      summary: |
        Stop the running pipelinerun for a cluster.
        If there is no running pipelinerun, do nothing and return success.
        A cluster can only have one running pipelinerun.
      responses:
        "200":
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/pipelineruns/{pipelinerunID}/log:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    get:
      tags:
        - pipelinerun
      operationId: getPipelineRunLog
      summary: |
        Get the specified pipelinerun's log for a cluster.
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                example: |
                  xxxxxxxxxxxx
                  xxxxxxxxxxxx
                  xxxxxxxxxxxx
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/pipelineruns/{pipelinerunID}:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    get:
      tags:
        - pipelinerun
      operationId: getPipelinerun
      summary: |
        Get the specified pipelinerun.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/PipelineRun"
                example: |
                  {
                      "data":
                      {
                          "id":3,
                          "title":"Feature123",
                          "description":"release big rocket",
                          "action":"builddeploy",
                          "status":"StatusCreated",
                          "gitURL":"ssh://git@cloudnative.com:22222/app/app-demo.git",
                          "gitBranch":"master",
                          "gitCommit":"4234324dsdjasljl43",
                          "imageURL":"",
                          "lastConfigCommit":"4234324dsdjasljl43",
                          "configCommit":"4234324dsdjasljl43",
                          "startedAt":"2021-11-07 11:19:54",
                          "finishedAt":"2021-11-07 11:19:54",
                          "canRollback": false,
                          "createBy":{
                            "userID":0,
                            "userName":"123"
                          }
                      }
                  }
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/pipelineruns/{pipelinerunID}/diffs:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    get:
      tags:
        - pipelinerun
      operationId: getPipelineRunDiff
      summary: |
        Get the specified pipelinerun's diff
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/PipelineRunDiff"
                example: |
                  {
                      "data":{
                          "codeInfo":{
                              "Branch": "master"
                              "CommitMsg": "last commit msg"
                              "CommitID":"6cb5e13a2d3c59f2283fc6b52771729691aa9fc3"
                              "Link": https://horizon.com/cloud-native/horizon/horizon/-/commits/feature/applications
                          },
                          "configDiff ": {
                            "from": "6cb5e13a2d3c59f2283fc6b52771729691aa9fc3"
                            "to": "6cb5e13a2d3c59f2283fc6b52771729691aa9fc3"
                            "diff":"@@ -1,7 +1,7 @@\n metadata:\n   name: web-api\n   namespace: cicd\n-  charVersion: v2.7.3\n+  charVersion: v2.7.4\n \n replicaCount: 2\n \n"
                          }
                      }
                  }
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/clusters/:%v/pipelineruns:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramClusterID"
      - $ref: "common.yaml#/components/parameters/pageNumber"
      - $ref: "common.yaml#/components/parameters/pageSize"
      - name: canRollback
        in: query
        schema:
          type: boolean
        description: whether the pipelinerun can rollback
    get:
      tags:
        - pipelinerun
      operationId: getClusterPipelineRuns
      summary: |
        Get pipelineruns of a cluster.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        $ref: "#/components/schemas/PipelineRun"
                      total:
                        type: integer
                example: |
                  {
                    "total": 1,
                    "items": [
                      {
                        "id": 1245735,
                        "title": "rg",
                        "description": "",
                        "action": "builddeploy",
                        "status": "ok",
                        "gitURL": "ssh://git@cloudnative.com:22222/xxx/springboot-demo.git",
                        "gitBranch": "jdk17",
                        "gitCommit": "da1a46ebfc9e48c7c4af4b89fe35bb209cd89883",
                        "imageURL": "",
                        "lastConfigCommit": "00e049bb2dc6f6ccee06e508e8a7c5f9ce71e875",
                        "configCommit": "5deefff34944b4780ae3c040bfeec29211904756",
                        "createdAt": "2022-12-30T12:03:01+08:00",
                        "updatedAt": "2022-12-30T12:03:38+08:00",
                        "startedAt": "2022-12-30T12:03:01+08:00",
                        "finishedAt": "2022-12-30T12:03:37+08:00",
                        "canRollback": false,
                        "createdBy": {
                          "userID": 667,
                          "userName": "admin"
                        }
                      }
                    ]
                  }
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/core/v2/pipelineruns/{pipelinerunID}/run:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    post:
      tags:
        - pipelinerun
      operationId: runPipelinerun
      summary: |
        Run the specified pipelinerun.
      responses:
        "200":
          description: Success
  /apis/core/v2/pipelineruns/{pipelinerunID}/forcerun:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    post:
      tags:
        - pipelinerun
      operationId: forceRunPipelinerun
      summary: |
        Force run the specified pipelinerun.
      responses:
        "200":
          description: Success
  /apis/core/v2/pipelineruns/{pipelinerunID}/cancel:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    post:
      tags:
        - pipelinerun
      operationId: cancelPipelinerun
      summary: |
        Cancel the specified pipelinerun.
      responses:
        "200":
          description: Success
  /apis/core/v2/pipelineruns/{pipelinerunID}/checkrun:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    post:
      tags:
        - pipelinerun
      operationId: createCheckRun
      summary: |
          Create a check run for the specified pipelinerun.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "name of check run"
                checkId:
                  type: integer
                  description: "check id of check run"
                status:
                  type: string
                  description: "status of check run"
                message:
                  type: string
                  description: "message of check run"
                detailUrl:
                  type: string
                  description: "detail url of check run"
      responses:
        "200":
            description: Success
    get:
      tags:
          - pipelinerun
      operationId: listCheckRuns
      summary: |
        List check runs of the specified pipelinerun.
      responses:
          "200":
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    total:
                      type: integer
                      description: "total number of check runs"
                    data:
                      type: object
                      properties:
                        items:
                          type: array
                          properties:
                              id:
                                  type: integer
                                  description: "id of check run"
                              name:
                                  type: string
                                  description: "name of check run"
                              checkId:
                                  type: integer
                                  description: "check id of check run"
                              status:
                                  type: string
                                  description: "status of check run"
                              pipilineRunId:
                                  type: integer
                                  description: "pipelinerun id of check run"
                              detailUrl:
                                  type: string
                                  description: "detail url of check run"
                              message:
                                  type: string
                                  description: "message of check run"
                              createdAt:
                                  type: string
                              updatedAt:
                                  type: string
  /apis/core/v2/pipelineruns/{pipelinerunID}/message:
    parameters:
      - $ref: "common.yaml#/components/parameters/paramPipelinerunID"
    post:
      tags:
        - pipelinerun
      operationId: createMessage
      summary: |
        Create a message for the specified pipelinerun.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: "content of check run"
      responses:
        200:
          description: "Success"
    get:
      tags:
          - pipelinerun
      operationId: listMessage
      summary: |
        List message of the specified pipelinerun.
      responses:
          "200":
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    total:
                      type: integer
                      description: "total number of message"
                    data:
                      type: array
                      properties:
                        id:
                          type: integer
                          description: "id of message"
                        pipilineRunId:
                          type: integer
                          description: "pipelinerun id of message"
                        content:
                          type: string
                          description: "content of message"
                        createdAt:
                          type: string
                        createdBy:
                            $ref: "#/components/schemas/MessageUser"
                        updatedBy:
                          $ref: "#/components/schemas/MessageUser"



components:
  schemas:
    MessageUser:
      type: object
      properties:
          id:
            type: integer
          name:
            type: string
          userType:
            type: string
    PipelineRun:
      type: object
      properties:
        action:
          type: string
          description: "action of pipelinerun"
          enum: ["builddeploy", "deploy", "restart", "rollback"]
        canRollback:
          type: boolean
          description: "whether this pipelinerun can be specified to rollback"
        configCommit:
          type: string
          description: "commit of config repository"
        createdAt:
          type: string
        createdBy:
          $ref: "common.yaml#/components/schemas/User"
        description:
          type: string
        finishedAt:
          type: string
        gitBranch:
          type: string
          description: branch of source code
        gitCommit:
          type: string
          description: commit of source code
        gitURL:
          type: string
          description: url of source code
        id:
          type: integer
        imageURL:
          type: string
          description: full url of image
        lastConfigCommit:
          type: string
          description: "last commit of config repository"
        startedAt:
          type: string
          description: "start time of pipelinerun"
        status:
          type: string
          enum: ["ok", "waiting", "failed", "canceled"]
        title:
          type: string
          description: "title of pipelinerun"
        updatedAt:
          type: string
          description: "update time of pipelinerun"
    PipelineRunDiff:
      type: object
      properties:
        codeInfo:
          type: object
          properties:
            branch:
              type: string
              description: "branch of source code"
            commitID:
              type: string
              description: "latest commit id of source code"
            commitMsg:
              type: string
              description: "latest commit message of source code"
            link:
              type: string
              description: "link of latest commit"
        codeDiff:
          type: object
          properties:
            diff:
              type: string
              description: "changed content of this pipelinerun"
            from:
              type: string
              description: "the last commit before the change"
            to:
              type: string
              description: "the last commit after the change"
