name: Lint & Unit Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read


jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3

  ut:
    strategy:
      matrix:
        go: [1.15, 1.16, 1.17]
    name: unit-test
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: ut
        env:
          COVERAGE_STANDARD: 60
        run: |
          COVERAGE=$(. .unit-test.sh)
          [[ "$?" == 0 ]] || exit 1
          [[ $(awk -v M=$COVERAGE -v N=$COVERAGE_STANDARD 'BEGIN{print(M>=N)?"0":"1"}') == "0" ]] && \
          echo "coverage is $COVERAGE" || {
            echo "coverage is $COVERAGE, is less than $COVERAGE_STANDARD"; exit 1
          }
